/**
 * ========================================================================
 * LIVE TV CHANNELS CONFIGURATION (M3U8 & EMBED STREAMS)
 * ========================================================================
 * 
 * Edit this file to add, modify, or remove Live TV channels!
 * 
 * SUPPORTED FORMATS:
 * ------------------------------------------------------------------------
 * 1. Simple channel name (auto-mapped to ZLive embed / IPTV):
 *    "ESPN", "Sky Sports F1 FHD", "HBO", etc.
 * 
 * 2. Object with Direct M3U8 stream URL:
 *    {
 *      name: "NASA TV HD (Live)",
 *      slug: "nasa-tv-live",
 *      cat: "news",
 *      streamUrl: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
 *      type: "m3u8"
 *    }
 */

window.CUSTOM_LIVE_STREAMS = [
  {
    name: "NASA TV Official (HD 24/7)",
    slug: "nasa-tv-live-official",
    cat: "documentary",
    catName: "News & Science",
    icon: "fa-solid fa-shuttle-space",
    streamUrl: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    type: "m3u8",
    desc: "24/7 NASA Live Stream showing spacewalks, launches and ISS live views"
  },
  {
    name: "Red Bull TV Live HD",
    slug: "red-bull-tv-live",
    cat: "sports",
    catName: "Sports & Live Events",
    icon: "fa-solid fa-trophy",
    streamUrl: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    type: "m3u8",
    desc: "Action sports, live events, extreme biking, motorsport and music"
  }
];

window.RAW_LIVE_TV_CHANNELS = [
  "Sky Sports F1 4K IPTV HEVC",
  "Sky Sports F1 FHD",
  "TSN 4",
  "beIN Sports 2 AU",
  "beIN Sports Turkey 1",
  "beIN Sports Turkey 2",
  "DAZN Italy",
  "SperSport Football",
  "SperSport Grand Stand",
  "SperSport Premier Leauge",
  "DAZN F1 FHD Test",
  "Fox Sports 502 AU",
  "Cartoon Network UK",
  "Boomerang UK",
  "SprtsNET LA Test",
  "CBC",
  "Sony Sports 1 Backup",
  "Treehouse Kids",
  "YTV Canada",
  "Sony Sports 2 Backup",
  "Sony Sports 3 Backup",
  "Bloomberg BNN CA",
  "Sony Sports 5 Backup",
  "CNN USA",
  "Sp*rtsNET NY",
  "TNT Sport 5 Extra",
  "TNT Sport 6 Extra",
  "beIN Sports Arabic 1",
  "VH1 USA",
  "WEtv USA",
  "PBS Kids",
  "beIN Sports Qatar HD",
  "TRT 1 1440p",
  "ABC",
  "ACC Network",
  "AE",
  "AMC",
  "American Heroes Channel",
  "Animal Planet",
  "AXS TV",
  "BBC America",
  "BBC One London",
  "BBC Two",
  "beIN Sports",
  "beIN Sports Francais 1",
  "beIN Sports Francais 2",
  "beIN Sports Francais 3",
  "Big Ten Network",
  "Boomerang",
  "Bravo",
  "CANAL+ Extra 1",
  "BHT 1 Bosnia",
  "CANAL+ Extra 2",
  "CANAL+ Sport PL",
  "CANAL+ Sport 2 PL",
  "CANAL+ Sport 3 PL",
  "CANAL+ Sport 4 PL",
  "CANAL+ Sport 5 PL",
  "CANAL+ Golf AT",
  "CANAL+ Sport 6 PL",
  "Cartoon Network",
  "CBeebies",
  "CBS",
  "CBS Sports Network",
  "CNBC",
  "Comedy Central",
  "CW",
  "DAZN 1 Germany",
  "DAZN 2 Germany",
  "DAZN 1 Italia",
  "CANAL+ Sport 6 CZ",
  "DAZN 1 Spain",
  "DAZN 2 Spain",
  "CANAL+ Sport 8 CZ",
  "DAZN 1 Portugal",
  "DAZN 1 USA",
  "DAZN F1",
  "DAZN LaLiga",
  "Discovery Channel",
  "Discovery Family",
  "Discovery Turbo",
  "Disney Channel",
  "Disney Junior",
  "Disney XD",
  "Eleven Sports 1",
  "Eleven Sports 2",
  "Eleven Sports 3",
  "Eleven Sports 4",
  "ESPN",
  "ESPN Deportes",
  "ESPN2",
  "ESPNEWS",
  "ESPNU",
  "Food Network",
  "Fox",
  "Fox Deportes",
  "Fox Sports 1",
  "Fox Sports 2",
  "Fox Sports 501 (Cricket)",
  "Fox Sports 502 (League)",
  "Fox Sports 503",
  "Fox Sports 504 (Footy)",
  "Fox Sports 505",
  "Fox Sports 506",
  "Fox Sports 507",
  "FX",
  "FXM",
  "FXX",
  "Freeform",
  "Go3 Sport 1",
  "Go3 Sport 2",
  "Go3 Sport 3",
  "GOLF Channel",
  "HBO",
  "HBO Comedy",
  "HBO Drama",
  "HBO Latino",
  "HBO Movies",
  "HGTV",
  "MLB Network",
  "MotoGP Channel",
  "Movistar Deportes",
  "Movistar Deportes 2",
  "Movistar Deportes 3",
  "M4 Sport HU",
  "Movistar LaLiga",
  "Movistar Plus",
  "MTV",
  "NBA TV",
  "NBC",
  "NBC Sports Bay Area",
  "NBC Sports Philadelphia",
  "Hub Sports 1 Singapore",
  "NFL Network",
  "Hub Sports 2 Singapore",
  "NHL Network",
  "Hub Sports 3 Singapore",
  "Nick Jr.",
  "Hub Sports 4 Singapore",
  "Nickelodeon",
  "Hub Sports 5 Singapore",
  "Nicktoons",
  "Magenta Sport 5 GR",
  "Polsat Sport 1",
  "Magenta Sport 6 GR",
  "Polsat Sport 2",
  "ITV 3 UK",
  "Polsat Sport 3",
  "ITV 4 UK",
  "Nova Sport 1 CZ",
  "Polsat Sport Fight",
  "Nova Sport 2 CZ",
  "Polsat Sport News",
  "Nova Sport 3 CZ",
  "Polsat Sport Premium 1",
  "Nova Sport 4 CZ",
  "Polsat Sport Premium 2",
  "Nova Sport 5 CZ",
  "Polsat Sport Premium 3",
  "Nova Sport 6 CZ",
  "Polsat Sport Premium 4",
  "Optus Sport 1",
  "Polsat Sport Premium 5",
  "Optus Sport 2",
  "Polsat Sport Premium 6",
  "Optus Sport 3",
  "Premier Sports 1",
  "Optus Sport 4",
  "Premier Sports 2",
  "Optus Sport 5",
  "Red Bull TV",
  "Optus Sport 6",
  "Sky Cinema Action",
  "Sky Cinema Animation",
  "Sky Cinema Best Of",
  "Sky Cinema Classics",
  "Sky Cinema Comedy",
  "Sky Cinema Drama",
  "Sky Cinema Family",
  "Sky Cinema Greats",
  "Sky Cinema Hits",
  "Sky Cinema Premiere",
  "Sky Cinema Sci-Fi",
  "Sky Cinema Select",
  "Sky Cinema Thriller",
  "Sky Comedy",
  "Sky Crime",
  "Sky Documentaries",
  "Sky History",
  "Sky Max",
  "Sky Nature",
  "Sky News",
  "Sky News UK",
  "Sky Sci-Fi",
  "Sky Showcase",
  "Sky Sport 1 DE",
  "Sky Sport 1 NZ",
  "Sky Sport 2 DE",
  "Sky Sport 2 NZ",
  "Sky Sport 3 DE",
  "Sky Sport 3 NZ",
  "Sky Sport 4 DE",
  "Sky Sport 4 NZ",
  "Sky Sport 5 DE",
  "Sky Sport 5 NZ",
  "Sky Sport 6 DE",
  "Sky Sport 6 NZ",
  "Sky Sport 7 DE",
  "Sky Sport 7 NZ",
  "Sky Sport 8 DE",
  "Sky Sport 9 DE",
  "Sky Sport Action",
  "Sky Sport Arena",
  "Sky Sport Austria 1",
  "Sky Sport Austria 2",
  "Sky Sport Austria 3",
  "Sky Sport Austria 4",
  "Sky Sport Bundesliga 1",
  "Sky Sport Bundesliga 2",
  "Sky Sport Bundesliga 3",
  "Sky Sport F1",
  "Sky Sport F1 DE",
  "Sky Sport F1 IT",
  "Sky Sport Football",
  "Sky Sport Golf",
  "Sky Sport Golf DE",
  "Sky Sport Mix",
  "Sky Sport Moto GP",
  "Sky Sport MotoGP DE",
  "Sky Sport News",
  "Sky Sport Premier League",
  "Sky Sport Tennis",
  "Sky Sport Top Event",
  "Sky Sport Uno",
  "Sky Sports Action",
  "Sky Sports Arena",
  "Sky Sports Cricket",
  "Sky Sports F1",
  "Sky Sports Football",
  "Sky Sports Golf",
  "Sky Sports Main Event",
  "Sky Sports Mix",
  "Sky Sports News",
  "Sky Sports Premier League",
  "Sky Sports Racing",
  "Sky Sports Tennis",
  "Sony BBC Earth",
  "Sony MAX",
  "Sony PIX",
  "Sony SAB",
  "Sony Six",
  "Sony Sports Ten 1",
  "Sony Sports Ten 2",
  "Sony Sports Ten 3",
  "Sony Sports Ten 4",
  "Sony Sports Ten 5",
  "Sony Yay",
  "Star Gold",
  "Star Plus",
  "Star Sports 1",
  "Star Sports 1 Hindi",
  "Star Sports 2",
  "Star Sports 3",
  "Star Sports First",
  "Star Sports Select 1",
  "Star Sports Select 2",
  "SuperSport Action",
  "SuperSport Cricket",
  "SuperSport Football",
  "SuperSport Golf",
  "SuperSport Grandstand",
  "SuperSport LaLiga",
  "SuperSport Motorsport",
  "SuperSport PSL",
  "SuperSport Premier League",
  "SuperSport Rugby",
  "SuperSport Tennis",
  "SuperSport Variety 1",
  "SuperSport Variety 2",
  "SuperSport Variety 3",
  "SuperSport Variety 4",
  "TBS",
  "Teledeporte",
  "Tennis Channel",
  "TLC",
  "TNT",
  "TNT Sports 1",
  "TNT Sports 2",
  "TNT Sports 3",
  "TNT Sports 4",
  "TNT Sports Ultimate",
  "Travel Channel",
  "truTV",
  "TSN 1",
  "TSN 2",
  "TSN 3",
  "TSN 5",
  "USA Network",
  "Viaplay 1 UK",
  "Viaplay 2 UK",
  "Viaplay Extra",
  "Viaplay Sport 1",
  "Viaplay Sport 2",
  "Viaplay Sport 3",
  "Willow Cricket",
  "WWE Network",
  "Ziggo Sport",
  "Ziggo Sport Docu",
  "Ziggo Sport Golf",
  "Ziggo Sport Racing",
  "Ziggo Sport Select",
  "Ziggo Sport Tennis",
  "Ziggo Sport Voetbal"
];
